/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gabriel.DSA;

import org.gabriel.DSA.DataStructure.S_LinkedList;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class S_LinkedListTest {
    @Test void linkedList() {
        S_LinkedList<Integer> ll = new S_LinkedList<>();

        assertEquals(10, ll.insert_last(10));
    }
}
